console.log('');
console.log('-> Package Source');
console.log('https://github.com/noder-jk/nodereactor');
console.log('https://www.npmjs.com/package/nodereactor');
console.log('');
console.log('-> Documentations');
console.log('https://NodeReactor.com');
console.log('');
console.log('-> Add-ons');
console.log('https://nodereactor.com/add-ons/themes/');
console.log('https://nodereactor.com/add-ons/plugins/');
console.log('');
console.log('-> Communities');
console.log('https://facebook.com/NodeReactorCMS');
console.log('https://facebook.com/groups/NodeReactorDevs');
console.log('');
console.log('');